### ISSUE TITLE
Add expander to show README below collection lines?

### ISSUE THREAD

**Issue by sammyjava** [legumeinfo/jekyll-legumeinfo#100]
This would be a click-n-show on the Collections page, with a down arrow to open a README view under the collection line, up arrow to close it, and still click on the collection name to go to the Datastore collection (maybe with a "go to datastore" indicator).

This would involve throwing some Javascript on the page to do so while doing an HTTP request to the Datastore to suck the full README, which should be pretty quick for most users if the LIS site is decently peered (I've never looked into how quickly requests get returned from legumeinfo.org but I presume it's not bad. If that's too slow, we can load the READMEs into the website under _data and use GitHub to serve them, which has pretty good peering and bandwidth. I download the READMEs now, anyway, to build the _data files locally, but I delete them when I'm done.)

I suppose this could be a pretty simple intial GraphQL example, although we don't have the full READMEs anywhere other than in files. But that's a Datasource.

**Comment by sammyjava** [comment]
Mockup:
![README-mockup](https://user-images.githubusercontent.com/5657219/167156458-562f5e5c-3bb4-42e5-8344-0ba0263f0a11.png)

**Comment by adf-ncgr** [comment]
+1 to using as an initial GraphQL implementation; IIRC Nathan's earlier prototype had slurped the datastore yamls. Ultimately having queries to metadata content would be empowering (presumably something like this would be the foundation for DSCensor 2.0 @ctcncgr )

**Comment by sammyjava** [comment]
> +1 to using as an initial GraphQL implementation; IIRC Nathan's earlier prototype had slurped the datastore yamls. Ultimately having queries to metadata content would be empowering (presumably something like this would be the foundation for DSCensor 2.0 @ctcncgr )

Slurped into what? (GraphQL isn't a database, it's a query language.) @nathanweeks  ? I suppose any tuple-store would be a fine place into which to slurp them. MongoDB would be my choice since I've been planning to learn it.

**Comment by adf-ncgr** [comment]
https://github.com/legumeinfo/datastore-graphql-demo

**Comment by sammyjava** [comment]
Ahhh, forgot about that. It uses the files themselves as the backing store and parses them on queries. Which is what I was suggesting. But I think maybe loading them into Mongo might be a nice option to enforce the data adhering to a schema *cough*. Notwithstanding our amazingly perfect validation....

**Comment by sammyjava** [comment]
And, of course, loading them into Mongo allows fancy things that one can do with the mines for data that ARE loaded in the mines, like: "Find all collections that include 'Embrapa 20' in their genotypes", but for all collections in the DS. Plus I bet it'd be a lot faster than querying the mines. (And I'd have to add genotypes into DataSet for that particular query to be useful, but it is easy to add all the README fields to DataSet if we went that way.)

**Comment by adf-ncgr** [comment]
going Mongo works for me (esp. since I won't likely have to lift a finger)

**Comment by sammyjava** [comment]
I may build a demo since I'm such a huge GraphQL expert these days. ;)
