### ISSUE TITLE
Add Tools link and landing page for GCViT instances

### ISSUE THREAD

**Issue by cann0010** [legumeinfo/jekyll-legumeinfo#113]
I'd like to get the GCViT instances linked from the tools menu.

Since we have four instances (and there will likely be more coming), I am thinking that we should have a landing page for them - maybe tools/gcvit/ ... which would have some instructions and pictures, much like the gcv landing page.

https://gcvit.soybase.org
https://gcvit.phaseolus.legumeinfo.org
https://gcvit.arachis.peanutbase.org
https://gcvit.cicer.legumeinfo.org

Intro text:
"GCViT: a multiple chromosome visualisation tool for visualizing resequencing or SNP array data. GCViT permits comparison of multiple accessions to a reference accession within a single dataset, to visually identify regions of similarities and differences across the genome."

There is also a tutorial ... which should probably be redone to be made more generic (and briefer):
https://youtu.be/B2gPVUipWo0

I am willing to work on this if needed, but that may need to wait until June 6, after submission of annual report and project plan.

**Comment by sammyjava** [comment]
I'm happy to take it on and preview it on dev.

**Comment by cann0010** [comment]
Thank you @sammyjava !

**Comment by sammyjava** [comment]
Right now we've got two tools categories: "Browse and Search" and "Sequence search". I'm wondering if we should add a category for more genetic-oriented tools.

**Comment by cann0010** [comment]
How about these categories:
```
Download/Query
  LIS Datastore
  LIS InterMines
  DSCensor Data Overviews

Visualize/Browse
  ZZBrowse GWAS/QTL
  CMap Map Viewer
  LIS Germplasm GIS Viewer
  Conekt Comparative Expression
  GCViT Diversity Browser
  Genome Context Viewer
  Gene Family Search

Sequence search
  LIS SequenceServer BLAST
  Funnotate: Annotate Your Sequences
```

**Comment by sammyjava** [comment]
Works for me, I'll punch those in.

**Comment by sammyjava** [comment]
Take a look at https://jekyll-dev.lis.ncgr.org/

**Comment by cann0010** [comment]
I like it! The categories make more sense to me. The GCViT page looks fine. I say "ship it."

**Comment by adf-ncgr** [comment]
One minor thing, fresh in my mind from a talk with Nevin where this came up frequently. Currently, none of the gcvit pages have links to take you back to their respective motherships. Therefore, per #66 I guess they ought to open in new tabs/windows? Otherwise looks good to me.

**Comment by sammyjava** [comment]
In production.

**Comment by sammyjava** [comment]
> One minor thing, fresh in my mind from a talk with Nevin where this came up frequently. Currently, none of the gcvit pages have links to take you back to their respective motherships. Therefore, per #66 I guess they ought to open in new tabs/windows? Otherwise looks good to me.

Yeah actually I just yanked the across-the-board target="_blank" in favor of harassing people to put the LIS header on their tools. So I'll fire up an issue for that. Having a "problem" will hopefully make it get "fixed."

**Comment by adf-ncgr** [comment]
Sounds good
