### ISSUE TITLE
Add LIS header to your tools!

### ISSUE THREAD

**Issue by sammyjava** [legumeinfo/jekyll-legumeinfo#116]
We need to add the standard LIS header to all tools so they fit into the _LIS solar system_ (not a galaxy, I've decided, since that's a much more random assemblage of stars and whatnot). So I'll list them here and the appropriate people should do as asked or at least start feeling guilty for not doing so.
- [x] LIS datastore -- (this one's a bit funky, but maybe as not funky as I think)
- [x] LIS InterMines -- already on the index page, added to the new mines as I promote them
- [x] DS Censor -- @ctcncgr 
- [x] LIS SequenceServer -- @nathanweeks  ?
- [x] Funnotate -- thanks, Sven!
- [x] GCV -- thanks, Alan!
- [x] ZZBrowse -- Sven is 2 for 2! 
- [x] CMap -- yikes. @nathanweeks ? I've no idea (FYI the title says "Compartive")
- [x] GIS viewer -- close, but logo links to itself, not back to www site -- dunno who maintains this now (@nathanweeks)
- [x] Conekt -- thanks, Sudhansu!
- [x] Gene family search -- Sven is 3 for 3!!
- [x] GCViT -- not sure about soybase/peanutbase but the ~~Arachis~~ Phaseolus and Cicer ones should have the LIS header @sdash-github (@nathanweeks)? 
- [x] Mines SequenceServer - @sammyjava

**Comment by sammyjava** [comment]
As for the header code, I have it somewhere on GitHub but I'm having trouble finding it. But just take a look at one of the above checked sites to see what they did. Here's what I have on the mines:
```
    <!-- LIS site nav -->                                                                                                                                                                    
    <div style="float:left;">                                                                                                                                                                
      <a href="https://www.legumeinfo.org/"><img src="https://www.legumeinfo.org/assets/img/lis-logo-small.png" alt="LIS - Legume Information System"/></a>                                      
    </div>                                                                                                                                                                                   
    <div style="float:left;margin-left:5px;margin-right:10px;padding-top:5px;font-family:ProximaNova,-apple-system,BlinkMacSystemFont,Segoe UI,Roboto,Helvetica Neue,Arial,sans-serif;">     
      <div style="font-size:20px; color:white;">LIS - Legume Information System</div>                                                                                                        
      <div style="font-size:12px; color:white;">Information about legume traits for crop improvement</div>                                                                                   
    </div>                                                                                                                                                                                   
    <!-- /LIS site nav --> 
```

**Comment by sdash-github** [comment]
Where is the GCViT repo? I can't find it, Can somebody point me to it; I couldn't find it under legumeinfo. 
After this I can attempt to put the logo and the link code. I think Andrew Wilki worked on the code while modifying it from CViTjs(Ethy)??

(The one I coded and maintained is the Drupal  module, lis_gcvit to put it inside an iframe, https://github.com/legumeinfo/lis_gcvit).

**Comment by adf-ncgr** [comment]
https://github.com/LegumeFederation/gcvit

**Comment by sammyjava** [comment]
@adf-ncgr @nathanweeks @sdash-github @ctcncgr Just a ping on this, I noticed that I'd totally forgotten to put the image link on the mine sequenceserver header.
