### ISSUE TITLE
remove banner with link to legacy site

### ISSUE THREAD

**Issue by adf-ncgr** [legumeinfo/jekyll-legumeinfo#130]
alternatively, I guess we might consider whether we should convert it to a statement that the legacy site is no longer available and encourage people to contact us if they have issues due to its removal; @cann0010 please weigh in on this

**Comment by cann0010** [comment]
My inclination is to remove it. Increase our default real estate. 
I can do the removal - probably Monday - unless someone else gets to it first.

**Comment by cann0010** [comment]
Changes have been made, and a PR initiated (https://github.com/legumeinfo/jekyll-legumeinfo/pull/131 ). Requested review from @sammyjava. Feel free to review as well, @adf-ncgr, if you have time before heading out of town.

**Comment by adf-ncgr** [comment]
I think this one was completed
