### ISSUE TITLE
links to legacy.legumeinfo.org now broken

### ISSUE THREAD

**Issue by adf-ncgr** [legumeinfo/jekyll-legumeinfo#132]
the taxa pages have links to resources like the older GBrowse/JBrowse that are no longer being hosted. We need to ensure that all these have corresponding JBrowse2 and then update the files to point to them (preferably using the autocontent scripts, though I have not yet tested that this functionality behaves as I expect)

**Comment by StevenCannon-USDA** [comment]
Commenting on this issue to re-elevate it. Links to all genome browser instances fail currently.
```
cd /usr/local/www/data/v2
grep legacy */*/about_this_collection/description*yml | wc -l
      43
grep legacy */*/about_this_collection/description*yml | cut -f1 -d':' | uniq | wc -l
      22
grep gbrowse */*/about_this_collection/description*yml | wc -l
      31
grep jbrowse */*/about_this_collection/description*yml | wc -l
      18
```

Unless `autocontent` obviates the `description_Genus_species.yml` files (and is ready to be put into production now), then all `description_Genus_species.yml` need to be updated.

**Comment by adf-ncgr** [comment]
this should be fixed on https://jekyll-stage.legumeinfo.org/ and will be on prod whenever that final hop of the new "release" takes place so I think I'll consider this closeable
