### ISSUE TITLE
How shall we deploy JS and HTML for Jekyll site?

### ISSUE THREAD

**Issue by sammyjava** [legumeinfo/jekyll-legumeinfo#137]
I'd like to figure this out, or have someone else figure it out. We talked about using a submodule to deploy "shims" so that we don't have to copy code to jekyll-legumeinfo from web-components. So one thought is that we roll what is now in /dev into /dist and have /dist become a submodule (which is built by npm as normal):
```
shokin@morangie:~/web-components$ ls dist-as-submodule/
controllers     index.js                          lis-linkout-element.d.ts                 lis-publication-search-element.js      lis-trait-search-element.d.ts      README.md
core            index.js.map                      lis-linkout-element.d.ts.map             lis-publication-search-element.js.map  lis-trait-search-element.d.ts.map  web-components.bundled.js
graphql.js      lis-gene-search-element.d.ts      lis-linkout-element.js                   lis-qtl-search-element.d.ts            lis-trait-search-element.js
html            lis-gene-search-element.d.ts.map  lis-linkout-element.js.map               lis-qtl-search-element.d.ts.map        lis-trait-search-element.js.map
index.d.ts      lis-gene-search-element.js        lis-publication-search-element.d.ts      lis-qtl-search-element.js              mixins
index.d.ts.map  lis-gene-search-element.js.map    lis-publication-search-element.d.ts.map  lis-qtl-search-element.js.map          models

shokin@morangie:~/web-components$ ls dist-as-submodule/html
core  examples  lis-gene-search-element.html  lis-linkout-element.html  lis-publication-search-element.html  lis-qtl-search-element.html  lis-trait-search-element.html
```
I know we only need `web-components.bundled.js` and `graphql.js`, but I don't think it's horrible to take those other files along for the ride, they're not huge. And then you see I've put `dev/*` into what would be `dist/html`.

This make any sense? Then we use web-components-dist in jekyll-legumeinfo with includes or symlinks.

**Comment by sammyjava** [comment]
Moved to jekyll-legumeinfo. Check out the gene-search branch layout: /assets/js and /tools/search. I went totally minimal on the JS files, maybe overboard.

**Comment by alancleary** [comment]
Looks pretty good. A couple thoughts on the assets/ directory:

- It may be worth adding some sub-directories to assets/js/ to keep things more organized, e.g. webcomponents/, graphql/, and uikit/.
- I think it makes sense to put the graphql queries in the same files as the functions that use them. This will reduce the numbers of files and imports.
- Assuming all the graphql files have been added to their own sub-directory, you could add an index.js file to that directory, which would allow everything to be imported through that one file in the templates (see the HTML files in the dist/ directory of the web-components repo for an example).

**Comment by sammyjava** [comment]
I've done the first two. I'm not sure we want to just automatically import any graphql Javascript files from an index file, when any particular component will only use a few of them. For example, gene search uses get-genes.js and get-gene-form-data.js, but  QTL or any other search won't. And there could get to be quite a few different graphql functions used by the web components.

The only JS that I see ALL components including is graphql.js. Even linkout-function.js is specific to things that have linkouts written for them.

**Comment by sammyjava** [comment]
I would totally not bundle them together, but I get that that's how things tend to be done with node apps. Everyone is assumed to be on 10 Mbps lines these days with browsers and computers that can handle massive amounts of code in huge RAM. Which I find irresponsible, but that's how the big companies have progressed.

**Comment by adf-ncgr** [comment]
not %100 sure but I think at least some of the bundlers support lazy loading (ie relevant chunks get loaded when there is actual demand for the functionality that they represent). Not that there isn't still ample room to complain about the cash value of caching...

**Comment by sammyjava** [comment]
I think this issue is closeable.
