### ISSUE TITLE
Incorporate Jekyll-theme Events/News updates

### ISSUE THREAD

**Issue by StevenCannon-USDA** [legumeinfo/jekyll-legumeinfo#139]
I noticed that Alan's Feb 23 changes regarding Events & News (date handling) in the Jekyll-theme haven't been pulled into this site. I think the main effect in practice is that in the existing site code, the date field (and/or the ISO-formatted date in the file name) gets used to set the "posted" date and to control ordering and display of the news items, whereas the actual posting date is typically long in advance of the thing in the news item (conferences, in our usage). 

Pulling the changes across ... @nathanweeks did this for Jekyll-Soybase by cherrypicking commits, so maybe could do the same here? Or maybe @sammyjava or @alancleary. I suppose I could try, but I am anxious that my git skills. aren't up to the task. Not urgent, but would be good to make use of those updates from Jekyll-theme.

**Comment by alancleary** [comment]
There's been talk of putting the LIS site back on the theme to avoid scenarios like this. Perhaps we can use this as an excuse to get that effort underway.

**Comment by sammyjava** [comment]
Seems like a useful task for someone.

**Comment by adf-ncgr** [comment]
more or less done
