### ISSUE TITLE
Collections and download pages are just duplicates

### ISSUE THREAD

**Issue by sdash-github** [legumeinfo/jekyll-legumeinfo#160]
Please see the links below. They are duplicates.
https://jekyll.dev.lis.ncgr.org/download/  
https://jekyll.dev.lis.ncgr.org/collections/  

Primary menu has link to Download.
Home and Contact pages have links to Collections.

**Comment by sammyjava** [comment]
Good eye! Yes, the transition from /collections to /download and not calling them "collections" was incomplete. See PR #161 for the fix.

**Comment by adf-ncgr** [comment]
fixed
