### ISSUE TITLE
JBrowse link from taxa/genus/ page shows error

### ISSUE THREAD

**Issue by sdash-github** [legumeinfo/jekyll-legumeinfo#162]
Only including two examples here. This is after track selection when the JB2 link is opened.

Page: https://jekyll.dev.lis.ncgr.org/taxa/phaseolus/ 
Link:  JBrowse2 phalu.G27455.gnm1 : JBrowse2 Linear Genome View
https://all-genera.lis.ncgr.org/tools/jbrowse2//?config=config.json&session=local-e7zRpfwWQ  
**Phaseolus: zooming in and force load helps but is this desirable presentation?**

Page:  https://jekyll.dev.lis.ncgr.org/taxa/pisum/  
Link:  JBrowse2 pissa.Cameor.gnm1 : JBrowse2 Linear Genome View
https://all-genera.lis.ncgr.org/tools/jbrowse2//?config=config.json&session=spec-{%22views%22:%20[{%22assembly%22:%20%22pissa.Cameor.gnm1%22,%20%22loc%22:%20%22pissa.Cameor.gnm1.chr1LG6:1-372165146%22,%20%22type%22:%20%22LinearGenomeView%22}]}  

![Screen Shot 2024-02-08 at 11 04 19 AM](https://github.com/legumeinfo/jekyll-legumeinfo/assets/3673723/7a4bd35d-644c-4ce9-8cc0-df13c06e3fdc)
![Screen Shot 2024-02-08 at 11 22 45 AM](https://github.com/legumeinfo/jekyll-legumeinfo/assets/3673723/891897a6-e0d7-40b7-a177-7f53c034138b)   
**Pisum: Zooming in and Reload fails to change anything?**

**Comment by adf-ncgr** [comment]
The all zoomed out behavior is expected, but open to ideas about what would make sense to do as a general solution for "interesting view applicable to any random genome off the datastore". @ctcncgr is already going through some level of contortion to present the whole chromosome view (by peeking into the fasta index to get a chromosome name and size).

As far as Pisum is concerned, that's a bug. See https://github.com/legumeinfo/LIS-autocontent/issues/26
I can fix it manually, but it will probably recur when autocontent is used again in its current form. Probably we have the same issue with Vicia faba now. Thanks for noticing it!

**Comment by adf-ncgr** [comment]
Pisum should be working now; turns out that the index file had been removed from the datastore (in addition to the other bug). Feel free to close or leave open if you want to discuss ideas for handling the other issue (all zoomed out behavior). Personally, I think all-zoomed-out would be OK if JBrowse would display something like a gene density histogram at that level (ie it's not the zoom level per se that's the issue, just the fact that we don't get to see anything that's meaningful when it first opens).

**Comment by adf-ncgr** [comment]
will add issue to autocontent for specifying first MB like soybase is doing.
