### ISSUE TITLE
Need content for /community, /contact, and /help

### ISSUE THREAD

**Issue by sammyjava** [legumeinfo/jekyll-legumeinfo#17]
This is a reminder that the /community, /contact/, and /help pages are currently empty. We need to decide what goes on those pages, or remove them from the site.

**Comment by cann0010** [comment]
Assignment accepted. Will probably tackle in the week of Jan 10.

**Comment by sammyjava** [comment]
@cann0010 be aware that I've added a Blog nav item for bloggy stuff, there are two stub examples on the dev site that were sorta copped from legfed: https://jekyll-dev.lis.ncgr.org/blog/

**Comment by cann0010** [comment]
Commencing on this task today ...

**Comment by sammyjava** [comment]
I think you finished this task, closing.
