### ISSUE TITLE
Need LIS-News Items

### ISSUE THREAD

**Issue by sdash-github** [legumeinfo/jekyll-legumeinfo#170]
Now that News and Events are behaving as expected we should update the news.  The latest news item now is Aug-2023. 
-- Soliciting any news worthy item/activity done since then from Andrew (@adf-ncgr) and Steven(@StevenCannon-USDA ). If you can give enough hints I can create the verbiage for you to do the refinements.  
-- Goal here is that our news page shouldn't indicate we are not doing much since the Jekyll site was dedicated.  
**(Please assign it to me after you are done with suggesting the news items.)

**Comment by StevenCannon-USDA** [comment]
@sdash-github - this isn't a typical news item, but I'd like to accommodate this request from Jack Okamuro -- either under News or Events. News seems slightly more appropriate to me.

16, April 2024: Job Announcement: National Program Leader for USDA-ARS National Plant Germplasm System, comprising plant genetic resource management, genetic enhancement and applied research programs related to plant genetic resource conservation and sustainable use of 200+ crops from 16,000+ species.  Apply by 04/26/2024: [https://www.usajobs.gov/job/783750200](https://www.usajobs.gov/job/783750200)

**Comment by sdash-github** [comment]
The news update process isn't properly working in my lis branch and so far we haven't figured out the reason. We will meet agin later and debug it more and as soon as it is fixed I will put the news item asap.

**Comment by sdash-github** [comment]
It seems(?) I can't review it although I assigned it to myself for a review. So,
@StevenCannon-USDA , can you please review it and then I can merge and create a release.

**Comment by sdash-github** [comment]
This is the pull request:
https://github.com/legumeinfo/jekyll-legumeinfo/pull/172

**Comment by sdash-github** [comment]
Closing issues after adding March 30 2024 news, site updates.
