### ISSUE TITLE
Add gene-name translator page, with new pangene lookup component

### ISSUE THREAD

**Issue by StevenCannon-USDA** [legumeinfo/jekyll-legumeinfo#184]
See https://www.soybase.org/tools/translate/ ... which will be changing when the web component is ready.

**Comment by alancleary** [comment]
@StevenCannon-USDA I believe @adf-ncgr handled this in PR #179. Is this correct?

**Comment by adf-ncgr** [comment]
Currently awaiting group review at https://jekyll-stage.legumeinfo.org/tools/search/pangene.html
(on tomorrow's meeting agenda)

**Comment by StevenCannon-USDA** [comment]
Beautiful! I hadn't seen the implementation at jekyll-stage. We can close this issue after review at the meeting on the 10th.
