### ISSUE TITLE
Handling attribution for images on site

### ISSUE THREAD

**Issue by sammyjava** [legumeinfo/jekyll-legumeinfo#22]
Need to develop a mechanism for attribution of originators for images we use, e.g. the species images.

**Comment by sammyjava** [comment]
So I'd like to stick with "stuff for the website is on the website" and a really easy way to implement attribution for the images is with a data file, say `_data/species_image_attribution.yml` containing something like
```
-
  gensp: glyma
  attribution: Bob Smith, Soybean Photographers International
  year: 2010
-
  gensp: glyso
  attribution: Jane Doe, Soja R Us
  year: 2015
```
If that sounds reasonable @cann0010 @adf-ncgr , I'll implement it. If a gensp has an entry, we show attribution like:  © 2010 Bob Smith, Soybean Photographers International. (This file will only be used for the gensp.jpg images of course, we can use other files for other images on the site.) @cann0010 if you'll toss me a couple attributions I'll get the file and display coded.

**Comment by cann0010** [comment]
That looks reasonable to me. The images live with the site (not the Data Store), so the attributions might as well follow suit. I'll gather some attributions in the next day or so.

**Comment by sammyjava** [comment]
This has been implemented with PR #27 into dev. https://jekyll-dev.lis.ncgr.org/ (with my two example placeholder attributions, to be updated as provided.)

**Comment by alancleary** [comment]
Is this being documented anywhere? All the data files used by the theme are documented in the theme's [readme](https://github.com/legumeinfo/jekyll-theme-legumeinfo/blob/main/README.md). I think it would be prudent to do the same for the LIS site.

**Comment by sammyjava** [comment]
I guess if it gets into the theme, yes. It's not in the theme since I don't add anything to the theme. I presumed that this is an LIS-specific add-on. If you think the theme merits this, I'll move it to the theme and document it. Or we can do that later. It is optional, of course, enabled with `layout: blog` and `layout: blog-item`. Your call, I'm happy to move it over.

**Comment by sammyjava** [comment]
The `site.categories.foobar` thing is powerful sauce.

**Comment by alancleary** [comment]
> There's a ton of stuff on the LIS site that isn't documented, this is a small part. When the thing reaches maturity I'll do a documentation spree.

I'm not going to die on this hill. But I will say the amount of time I spend reading other people's code is ridiculous.
