### ISSUE TITLE
mechanism (blog?) for featuring new tools/user stories to replace the legfed blog 

### ISSUE THREAD

**Issue by adf-ncgr** [legumeinfo/jekyll-legumeinfo#25]
assuming we don't want to keep using the legumefederation.org site for this purpose (or maybe we do?), then we ought to have something roughly similar on the new jekyll site.

**Comment by alancleary** [comment]
This is super easy with Jekyll. In fact, the news and announcements pages are technically Jekyll blogs. See the docs for details: https://jekyllrb.com/docs/step-by-step/08-blogging/

**Comment by adf-ncgr** [comment]
thanks, I was hoping that would be the case!

**Comment by sammyjava** [comment]
I've added a Blog nav item and created two stub posts off two on legfed as minimal examples. There isn't really room on the home page to stack a Blog Posts card under News and Announcements, as you can see it's lost "below the fold", so I'll need to tighten up the CSS on those cards if we want them to stack more tightly, which are currently given by the theme's uk-card styles. Although I'm overriding practically everything from the theme by now, I'm not keen to tweak the styling just yet. But it's in place, and you can practice creating blog posts in your own branch. (FYI, right now main is really far behind, but I've got a PR in place for Nathan to merge dev into main so we can see the latest-greatest on jekyll-stage.legumeinfo.org.)

**Comment by sammyjava** [comment]
(By the way, https://jekyll-dev.lis.ncgr.org/ updates every 10 minutes from the dev branch, so my Blog add will show at 17:00.)

**Comment by alancleary** [comment]
I'm not sure where the code you mentioned lives but a gotcha you may have to look out for is that announcements and news are also posts. So if you want to create a blog card and blog landing page you'll need to filter the posts variable to only show _blog_ posts. Here's an example from the theme's news card: https://github.com/legumeinfo/jekyll-theme-legumeinfo/blob/main/_includes/news-card.html#L11

**Comment by sammyjava** [comment]
https://github.com/legumeinfo/jekyll-legumeinfo/blob/dev/_includes/blog-card.html
https://github.com/legumeinfo/jekyll-legumeinfo/blob/dev/_layouts/blog-item.html
https://github.com/legumeinfo/jekyll-legumeinfo/blob/dev/_layouts/blog.html
https://github.com/legumeinfo/jekyll-legumeinfo/blob/dev/blog/index.html
https://github.com/legumeinfo/jekyll-legumeinfo/blob/dev/blog/_posts/2018-09-10-macrosynteny-gcv.md
https://github.com/legumeinfo/jekyll-legumeinfo/blob/dev/blog/_posts/2019-02-25-visualizing-genomes.md

Viewable on https://jekyll-dev.lis.ncgr.org/

**Comment by alancleary** [comment]
Cool. It looks like you already took care of it.

I hadn't considered that GitHub would process the `.md` files and display them like a readme. It's pretty cool to see the posts' front matter in a table like that!
