### ISSUE TITLE
Link collections and README synopses on site?

### ISSUE THREAD

**Issue by sammyjava** [legumeinfo/jekyll-legumeinfo#29]
I've added this to tomorrow's LIS agenda, but in the interest of keeping track of things with issues, here's the demo:

http://dev.lis.ncgr.org:50030/collections/Arachis/hypogaea/

The idea being that it's perhaps a bit more convenient (FAIRer?) to see what's in the DS on the website than clicking through the DS directories, e.g. https://legumeinfo.org/data/v2/Arachis/hypogaea/genomes/

Although I'm fine with that if we don't see an advantage to having collection synopses on the website. Same data, different presentation, nothing particularly new. It does expose typos, misspellings, other mistakes in the synopses a bit better perhaps, and maybe encourages us to write them in a more consistent manner. But that's a side benefit.

If we do this, by default Google Search will pull up both the site and datastore links, while right now it's just the DS links on a hit against a synopsis. (Search on "Genome assembly for peanut cultivar Shitouqui" for example). But we can tell Google not to index these pages on the site if we only want direct hits on the DS.

**Comment by adf-ncgr** [comment]
I love it!
