### ISSUE TITLE
Versioned releases

### ISSUE THREAD

**Issue by alancleary** [legumeinfo/jekyll-legumeinfo#4]
One thing we need to discuss before going live with the Jekyll site is how we want to tag releases. Historically we've done our best to make a release each month, ideally around the same time. However, we've also had one-off releases in-between to fix bugs/errors or when there's something new we're excited about and want to get into production sooner than the next release.

For these reasons, I think our release tags should use calendar dates as the beginning of the release version, but we should also include MINOR and PATCH (MICRO) numbers, i.e. semantic versioning (MAJOR.MINOR.PATCH) where the rollover date is the MAJOR "version". For example, `2021-07-05.1.3`. This tag indicates that the site was rolled over on July 5, 2021, but we added a new feature later and made 3 patches after that.

Are there any thoughts or opinions on this? Here's a website that discusses a few different options for using calendar dates as version numbers: https://calver.org/.

@cann0010 @nathanweeks @adf-ncgr

**Comment by adf-ncgr** [comment]
"When to use CalVer:
...
Does your project feature a large or constantly-changing scope?
...
If you answered yes to any of these questions, CalVer's semantics make it a strong choice for your project.
"

I'm sold.

**Comment by nathanweeks** [comment]
CalVer is a good choice. Since this is a static site, where the latest tagged release is probably the one that will always be deployed, I suspect there may not be as much benefit in attempting to distinguish between MINOR and PATCH versions for a semantic versioned suffix. It may suffice to adopt an numerically-increasing single-digit suffix, with a `.0` implied for the first tag on a given date (e.g., `2021-07-05`, then `2021-07-05.1`, then `2021-07-05.2`...)

But I'm open to other ideas.

**Comment by adf-ncgr** [comment]
sounds good to me. hopefully we'll never have to debate whether 2021-07-05.10 is actually larger than 2021-07-05.1

**Comment by nathanweeks** [comment]
On second thought, an explicit `.0` (`2021-07-05.0`) might make parsing easier for any automated processes (CI / CD) that reference these tags?

**Comment by alancleary** [comment]
I guess I was thinking we would use the MINOR number for new features and the PATCH number for bug fixes. I can think of a few times we've released new features between rollovers, so that's my case for the minor number. At the end of the day, though, it's just semantics. So if we decide we want one number to indicate any release between rollovers (new features, patches, or otherwise) then that's fine.

Do we want to drop the day from the date? Historically we've had a monthly release cadence (or slower) so the day may be gratuitous. Then we would have something like `2021-07.0`.

**Comment by sammyjava** [comment]
I see us doing promotions more often than once a month (which is arbitrary and a bit silly for a more dynamically updated site) so I say we keep the day in the tag.  Plus a sub-day piece since one often fixes something an hour later.
```
2022-04-04.0
```
would be the Day 0 tag.

**Comment by sammyjava** [comment]
@nathanweeks we think this is the tag format in an NCGR cabal today, speak now or forever or at least a little while hold your peace. :)

**Comment by nathanweeks** [comment]
@sammyjava That tag convention LGTM. Is it OK to forego enforcement at the GitHub Action and/or client-side git hook level)for now, to allow for some flexibility (e.g., `2022-04-04.1_test` or `2022-04-04.1_revert`), or should that convention be enforced at some level?

**Comment by sammyjava** [comment]
@nathanweeks well I think that if a tag promotes the site to www.legumeinfo.org it should be a strictly conformant tag. But if you're talking about pre-launch testing, sure, whatever you'd like to use. Seems to me once we're in production there'd be no reason to use anything other than production tags.

**Comment by nathanweeks** [comment]
@sammyjava with no prior experience actually implementing this, I'll propose preventing non-conformant tags from being pushed from the client with a pre-push hook (to make it immediate & obvious that a production site won't be built from the non-conformant tag). I'll have a go at a PR.

**Comment by sammyjava** [comment]
Did this morph into implementing validation of tags? Or should we just close it since we're in production with the agreed-upon tag format? (Plus, it's easy to change them - I did so recently on an update with a non-conformant tag.)

**Comment by nathanweeks** [comment]
I vote to close for now, and reconsider enforcement if it becomes an issue. (If anyone seconds, please go ahead and close the issue)

**Comment by adf-ncgr** [comment]
thirded (as I think @alancleary's thumb indicates seconding). closing.
