### ISSUE TITLE
Taxa dropdown menu inconsistencies

### ISSUE THREAD

**Issue by alancleary** [legumeinfo/jekyll-legumeinfo#51]
In the dev branch, the taxa dropdown menu in the full-size navbar has a horizontal divider, the taxa dropdown menu in the medium sized (lower) navbar does not. Also, the divider uses [a custom class](https://github.com/legumeinfo/jekyll-legumeinfo/blob/dev/_includes/global-stylesheets.html#L27). UIkit provides [its own class](https://getuikit.com/docs/nav#header-and-divider) for this:
```html
 <li class="uk-nav-divider"></li>
```
This should be the preferred class for horizontal dividers in dropdown menus.

I'll note that the menus in the `navbar-menu.html` and `navbar-lower-menu.html` can be kept in sync by putting all the `<li>...</li>` tags in a separate `navbar-menu-items.html` file and then including it in place of the `<li>...</li>` content in the `navbar-menu.html` and `navbar-lower-menu.html` files. For example, `navbar-menu.html` would then be:
```html
<ul class="uk-navbar-nav uk-visible@l">
    {% include navbar-menu-items.html %}
</ul>

<a href="#off-screen-menu" class="uk-navbar-toggle uk-hidden@s" uk-navbar-toggle-icon uk-toggle></a>
```

**Comment by sammyjava** [comment]
Thanks, done. One reason I dropped the menu-items include was the tweak on off-screen-menu to add "View All" links. But now I think that a phone really shouldn't have a massive nav with subnav stuff so I've simplified the off-screen-menu to only hold links to the main pages, which is easier to deal with on a small device. I think that's more in line with what one expects from a hamburger menu.
