### ISSUE TITLE
Dev site needs review

### ISSUE THREAD

**Issue by sammyjava** [legumeinfo/jekyll-legumeinfo#53]
Please review the dev site https://jekyll-dev.lis.ncgr.org/ by Wed, March 2 and indicate that you've done so below.
- If there are things you want to fix, fix them on your own branch and submit a PR to dev.
- If there is something you need someone else to fix, post a separate issue about it to this repo.
- If you just want to make a comment that does not require any action, do so below.
- [ ] Alan
- [ ] Andrew
- [ ] Connor
- [ ] Jacqueline
- [ ] Nathan
- [x] Sam
- [x] Steven
- [x] Sudhansu
- [x] Sven
- [ ] Wei

**Comment by sammyjava** [comment]
@alancleary @nathanweeks @adf-ncgr @cann0010 @weihuang12 @ctcncgr @sdash-github @jd-campbell @svengato

**Comment by svengato** [comment]
I did not see the part about making a pull request from a new branch, and committed the ZZBrowse blog post changes directly to dev. Let me know if I need to undo that.

**Comment by sammyjava** [comment]
No, that's fine and meant to be a normal routine for things like blogs and other content.

**Comment by sdash-github** [comment]
Review of LIS-Jekyll-Site as on 2022-03-01
--------------------------------------------

Header
----------
-- "Information about legume traits for crop improvement". Should we now include genomics here, '…legume genomics and traits for crop improvement'?

Home page
---------------
-- Font color is too light; the left panel is worse than the main panel.

-- Left panel may use a different shade like current site.

-- The main menu tabs' font color could be stronger too to bring out contrast between light green bkgd and white fonts. (Possibilities: shaded tabs like current site, bold, different color/darak, etc.)

-- Link to prior version could be made prominent at least for 1-2 years. **Already has mentioned it in the group and Alan is handling it.

-- That there is a right panel (news, announcements, etc.) is not apparent until I widen my window beyond what is normal for me (this is more exaggerated here than in the current site).

Taxa page
--------------
-- Arachis should follow the rest by mentioning the common name (peanut, groundnut) rather than an explanation of its ocurrence.  

-- The 2nd heading, "Special-focus genera and data sets": the data sets seems to be a misfit to me unless there is a plan to include data sets in addition to these special category species under this subheading.

-- First heading (containing significant crop and model species). Should be crops.

-- Suggestion: could it be two columns rather than lots of empty space to the right!

Collections Page
-----------------------
-- Arachis like in /taxa page needs a common name.
-- Too much empty space to the right.

Tools Page
---------------
-- The InterMines descriptions need improvement to indicate what to expect from a tool.

Community page
-----------------------
-- If we are mentioning soybase, we should also mention PeanutBase.
-- I think Ethy and I should be mentioned in LIS alums.

**Comment by svengato** [comment]
Once the production Funnotate is working, I plan to add it under Browse and Search (in _data/tools.yml). Or should it go under Search Sequences Against Sequence Databases?

**Comment by cann0010** [comment]
@svengato - Tools / Browse and Search seems right to me.
I think it would also be good to add consensus gene family sequences as a target within SequenceServer - but this could just live among the other targets (@nathanweeks). (Incidentally, I have found that hmmemit does a poor job of generating consensus sequences; it is prone to "stutters" in the vicinity of indel locations. EMBOSS cons does a better job)
It may also make sense to add Funnotate to "Tools and resources for the genus as a whole" under each Collection.

**Comment by svengato** [comment]
How about listing the Funnotate search page under Browse and Search, and the Funnotate home page under Search Sequences Against Sequence Databases?

**Comment by cann0010** [comment]
@svengato - I don't think I have seen the new Funnotate. Is a dev instance accessible?

**Comment by svengato** [comment]
http://dev.lis.ncgr.org:50080/shiny/Funnotate/

**Comment by cann0010** [comment]
Seeing the dev link ... yes, I think it would be appropriate to put Funnotate/ under Tools / SEARCH SEQUENCES
... and **a variant of** Funnotate/?search under Tools / BROWSE AND SEARCH.
The "functional keywords" search page (http://dev.lis.ncgr.org:50080/shiny/Funnotate/?search): I don't think that is quite sufficient as a standalone entry into the gene families. Would it be reasonable to put the same text-entry search into a separate Gene Family search page? I think someone dropped into Funnotate/?search and expecting gene families will wonder "What is Funnotate and why am I here?" I don't think this confusion would be present for someone coming via the Funnotate home page.

**Comment by svengato** [comment]
Pull request in progress - adding the Funnotate search and home pages to _data/tools.yml seems to cover it. If there is still interest in adding it to "Tools and resources for the genus as a whole", that can be the second iteration.

**Comment by adf-ncgr** [comment]
yes, I think so

**Comment by sammyjava** [comment]
Yes, I say all public apps linked from the LIS site should be on legumeinfo.org for consistency. This requires a DNS update by Rex: a CNAME pointing zzbrowse to lis.ncgr.org (hardy). I think @nathanweeks usually initiates those. You can add zzbrowse.legumeinfo.org to the Apache config as a ServerAlias and it'll work once requests head that way. No need to remove zzbrowse.lis.ncgr.org, that can always be available as a backup.

**Comment by adf-ncgr** [comment]
The DNS entry for zzbrowse.legumeinfo.org already exists, we just need to tweak the link target

**Comment by sammyjava** [comment]
Indeed, and it works, I'll update the link.

**Comment by adf-ncgr** [comment]
thanks! one of these days, I'll get back into editing "code"

**Comment by cann0010** [comment]
I have reviewed the site and have made a PR to fix minor text issues on the index page. Also tweaked link names in Tools.

For the two new Funnotate links (/shiny/Funnotate/ and /shiny/Funnotate/?search), I think these are good candidates for I-framing ... unless they will be integrated as web components? Maybe similarly for DSCensor and SequenceServer. Each of these has minimal-to-no menu system of their own, so I think they ought to adopt the parent site's menu environment. What this would look like (taking SequenceServer as the example): https://dev.soybase.org/tools/blast/
... and the code at https://github.com/soybase/jekyll-soybase .
Mentioning @alancleary and @svengato for your opinions. If we do this, the tools.yml would be restructured a bit to indicate link type.

**Comment by svengato** [comment]
This link is not working,
https://dev.soybase.org/tools/blast/

I would be concerned about the user needing to scroll if the application is too large to fit in the iframe, is there a way around this?

**Comment by svengato** [comment]
It also looks like the user would not be able to go directly to deeper pages (old uploads, jobs, phylograms) unless they knew the Funnotate URL and opened a separate window or tab.

**Comment by adf-ncgr** [comment]
regarding the link to soybase blast, it is working for me. Not sure I understand the scrolling concern, but the fact that the iframe hides URLs (and therefore is not that friendly to people wanting to bookmark or link in) is a good point to consider

**Comment by sammyjava** [comment]
I'll mostly stay out of the "to iframe or not to iframe" Hamletian dilemma, but I personally think a mix of standalone tools and iframed tools is a bad idea - hard to maintain, with drawbacks as given above. I'd prefer that people modify "plain white" standalone tools with HTML that provides a way back to the main site if needed. Perhaps just a clearly visible link to legumeinfo.org. I've generally not felt that heroic efforts to ensure that users "stay on the site" are warranted, especially if the link launches the new site in a new tab.

We don't have a spec that says what tools need to have to qualify for LIS site linkage, but we could certainly develop one so that we don't have to make decisions on a tool-by-tool basis. My assumption is that they are perfectly respectable standalone webapps, and that they're launched in a new browser tab so users can sally forth with the tool with the LIS site remaining handy.

**Comment by sammyjava** [comment]
SequenceServer: an example of a webapp that is easily "reskinned" to look like the LIS site and have the main nav links. Running it in an iframe to avoid having to "skin" it is, IMO, a bad choice. I'm happy to re-skin the mine SequenceServer as an example.

**Comment by adf-ncgr** [comment]
I'd be happy to see you put some skin in the game. It would be nice if all of the "standalone" apps that we're developing or re-skinning took a similar approach (e.g. the little icon in the upper left hand that gcv uses to let people get back to where they once belonged...)

**Comment by sammyjava** [comment]
OK, I'll add to my to-do list. It'll vary from app to app, of course. It's easy to edit https://github.com/wurmlab/sequenceserver/blob/master/views/layout.erb in this case.

**Comment by svengato** [comment]
Would it be sufficient to add a subtitle like
&bull; An element of the [Legume Information System](https://jekyll-dev.lis.ncgr.org/) &bull;
to the Funnotate and ZZBrowse headers?

**Comment by cann0010** [comment]
I'm OK with some minimal common nav elements that link the apps back to the main site. The GCV header seems like a good example.

**Comment by svengato** [comment]
I added an LIS icon/link to Funnotate and ZZBrowse, similar to the one in GCV.

**Comment by adf-ncgr** [comment]
Looks good to me; however, it seems my nightmare of a world of links that always open into new windows will-I nill-I is quickly becoming reality. I'd still like to see us limit this to things that are "really" going off-site (ie going from legumeinfo.org to *.legumeinfo.org would not count). Discussion was begun here:
legumeinfo/jekyll-theme-legumeinfo#15 
but I see @sammyjava said it was more appropriate as an issue for this repo so I'll open a separate one here to try to achieve consensus

**Comment by nathanweeks** [comment]
> I added an LIS icon/link to Funnotate and ZZBrowse, similar to the one in GCV.

@svengato when https://zzbrowse.legumeinfo.org/ loads in Chrome 99.0.4844.51, Google Translate offers to translate the site from Polish to English. Perhaps changing the `<html>` tag to `<html lang="en">` might help Chrome guess the correct language?

**Comment by svengato** [comment]
I have the same version of Chrome, and it does not ask for a translation.
Does anyone else see this behavior?

A quick search suggests this is a sporadic problem with Chrome, going back
to at least 2013. I am seeing suggestions like
  <html lang="en" class="notranslate" translate="no">
and will see if there is a way to enforce this in Shiny applications.

**Comment by adf-ncgr** [comment]
I think I had seen it also recently, maybe after you added some headings; but when it turned out that ZZBrowse is Polish for ZZBrowse, I decided it was innocuous.

**Comment by svengato** [comment]
You mean innocuousz?

**Comment by sammyjava** [comment]
Polish is a perfectly fine language.

**Comment by sammyjava** [comment]
Closing this, enough time has elapsed and I applied some of Sudhansu's recommendations which are now on dev.

**Comment by alancleary** [comment]
@sammyjava I'm about to make a PR that updates all the styling related issues I'm on the hook for. While updating the code I noticed there's now left sidebar menus for taxa and collections but those respective pages are using the tools left sidebar menu instead of their own. Is this intended? I can wrap a fix into my PR if they are in fact supposed to use their own sidebar menus.

**Comment by sammyjava** [comment]
At one point I had it working so you'd see tools if you were on the main Taxa page but you'd see taxa if you were on a specific genus page, but that went away when I fixed the data generator. So go ahead and change it to show the left sidebar menu corresponding to the section: Taxa shows taxa, Collections shows collections, all others show Tools. Or I can do it after your PR.

**Comment by alancleary** [comment]
OK. I fixed it. Also noticed Community is the only top-level page that doesn't have a left sidebar menu. Should this have the tools menu as well?

**Comment by sammyjava** [comment]
Yeah Tools should be the default.

**Comment by alancleary** [comment]
There is an empty h1 and p tag on every taxa page. Looking at the template these pages are generated from, it looks like the `genus_resources` and `genus_resources.display_name` for a particular genus are supposed to go here. Grepping the `_data` for these values returns nothing. Should these tags be removed?

**Comment by alancleary** [comment]
> Oh yeah, that's detritus from before I build the DS description loader and reconfigured those files. Remove/commit for your current PR.

OK. I deleted the tags in question, though I nearly deleted a bunch of other lines using the `genus_resources` variable before realizing they actually have values at compile time! Maybe consider documenting the structure of these data and how they're generated...

**Comment by sammyjava** [comment]
Yeah I'll add a README to the _scripts directory that shows what those contain. As you saw, genus_resources.name and genus_resources.display_name vanished when genus_resources became a straight-up copy of the DS genus description YAML.
