### ISSUE TITLE
Tools: specify navigation header for tools

### ISSUE THREAD

**Issue by sammyjava** [legumeinfo/jekyll-legumeinfo#66]
We've agreed that there needs to be consistency in the navigation on tools so that users can easily get back to the main Jekyll site. When that navigation is present, we no longer need to launch a new window from the main site tools link. I expect that updating all of the tools will take time, so tools that do not adhere to the spec will need to launch a new window until they are updated.

This is NOT a blocker for site launch.

**Comment by sammyjava** [comment]
https://dev.lis.ncgr.org/sequenceserver/

Inspired by GCV. The idea is to have the linked LIS logo with the words on the left side of every tool's nav. The code is written with inline styles and a designated spot to put your tool's navigation, for example:
```
      <!-- LIS site nav -->
      <div style="float:left;">
        <a href="https://legumeinfo.org/"><img src="http://dev.lis.ncgr.org:50030/assets/img/lis-logo-small.png" alt="LIS - Legume Information System"/></a>
      </div>
      <div style="float:left;margin-left:5px;padding-top:5px;font-family:ProximaNova,-apple-system,BlinkMacSystemFont,Segoe UI,Roboto,Helvetica Neue,Arial,sans-serif;">
        <div style="font-size:20px">LIS - Legume Information System</div>
        <div style="font-size:12px">Information about legume traits for crop improvement</div>
      </div>
      <!-- /LIS site nav -->
      <div style="float:left;margin-left:20px;">
        <!-- your tool nav -->
        <a class="navbar-brand" href="https://sequenceserver.com" target="_blank">
          <img class="logo" src="SequenceServer_logo.png" alt="sequenceserver_logo">
          <small>
            <%= SequenceServer::VERSION %>
          </small>
        </a>
        <!-- /your tool nav -->
      </div>
```
Comments?

**Comment by cann0010** [comment]
I think I like it.

**Comment by sammyjava** [comment]
https://dev.lis.ncgr.org/soymine/begin.do

That's how it looks applied to SoyMine without any tweaks (like switching to white rather than black text). As another example.

**Comment by sammyjava** [comment]
Not having heard any vociferous opposition to this, I think I'll document it in the README today and start switching tools that include it to not launching in new browser tabs from the main LIS site. Speak now or for some unspecified amount of time hold your peace.

**Comment by adf-ncgr** [comment]
currently not displaying well for me, due to image being served from http while pages being served via https, but can imagine it looking good; I assume this will not be the case when it gets rolled out, so not constituting objection...
<img width="563" alt="image" src="https://user-images.githubusercontent.com/2009605/157520853-a4007c32-6ce3-4df4-8aa9-f80114a92b47.png">

**Comment by cann0010** [comment]
OK in my view of it:
<img width="628" alt="Screen Shot 2022-03-10 at 11 09 42 AM" src="https://user-images.githubusercontent.com/3588740/157717503-bf44f21a-ddca-46c3-961f-bb4de8f040d8.png">

**Comment by sammyjava** [comment]
Yeah, just a temp example using the shokin instance. The spec will say https://legumeinfo.org//assets/img/lis-logo-small.png. I'll close this and write it up and implement it on the dev mines.
