### ISSUE TITLE
standalone GCV deployment 

### ISSUE THREAD

**Issue by adf-ncgr** [legumeinfo/jekyll-legumeinfo#68]
load.sh script is updated to include representative genomes for all LIS species, but the push did not seem to auto-deploy by the github action you set up; probably due to something I've done wrong (although I did test the load script was functioning locally before I pushed it). 

One other thing that needs some attention before we go live with this, macrosynteny is basically timing out due to the large number of small scaffolds associated with some of the genomes. I have a workaround hack that could be applied, but I think there's a better approach that could probably solve the issue that I will try to discuss on Monday with @alancleary

**Comment by nathanweeks** [comment]
[First attempt](https://github.com/legumeinfo/gcv/actions/runs/1942105241/attempts/1) apparently failed due to https://github.com/docker/compose/issues/8544 . Needed to use enable multiplexing (adding ControlMaster/ControlPath in the github action runner's ~/.ssh/config) to resolve.

**Comment by sammyjava** [comment]
I am so glad I live a docker-free life.

**Comment by adf-ncgr** [comment]
When the docker rapture comes, @sammyjava will be "left behind"; looks like gcv.legumeinfo.org is working well for microsynteny and @alancleary will be working on the macrosynteny performance issue in the next day or two. 

One question I have for @nathanweeks : it appears the deploy-from-square-one represented by [sixth attempt](https://github.com/legumeinfo/gcv/actions/runs/1942105241) took ~15min most of which I imagine was taken up by the loading of the redis db. Do you have in mind that we will be OK to do this (or worse, as the never-ending stream of genomes keep flowing) for every update? Some updates may not even be data-related (e.g. I noticed some of the examples given in the config use an old naming scheme that no longer works, so I will be fixing that). I like the basic idea of a reproducible data build, but I also see some advantages to be gained by the older strategy of dumping the redis db and reusing it. Wondering if there is a happy medium, e.g. if the redis db could be dumped and the loader script could test for existence of a given genome in the db before requesting an addition (so that only when we added new genomes to the load script would they take up time getting added). Not a blocker, but maybe something to revisit so that the docker heathen do not have further occasion to mock us...

**Comment by nathanweeks** [comment]
> One question I have for @nathanweeks : it appears the deploy-from-square-one represented by [sixth attempt](https://github.com/legumeinfo/gcv/actions/runs/1942105241) took ~15min most of which I imagine was taken up by the loading of the redis db. Do you have in mind that we will be OK to do this (or worse, as the never-ending stream of genomes keep flowing) for every update?

15 minutes is acceptable to me (actually, impressively fast). If the data loading performance scales linearly with the number of genomes, we'll probably be OK for a while before we have to consider optimization in this regard.

> Some updates may not even be data-related (e.g. I noticed some of the examples given in the config use an old naming scheme that no longer works, so I will be fixing that). I like the basic idea of a reproducible data build, but I also see some advantages to be gained by the older strategy of dumping the redis db and reusing it. Wondering if there is a happy medium, e.g. if the redis db could be dumped and the loader script could test for existence of a given genome in the db before requesting an addition (so that only when we added new genomes to the load script would they take up time getting added). Not a blocker, but maybe something to revisit so that the docker heathen do not have further occasion to mock us...

When a front-end service is updated, the reload of the redisearch service redis db would be done only because it's currently being forced in the `docker compose up` command via the `--force-recreate` and `--renew-anon-volumes`:

https://github.com/legumeinfo/gcv/blob/8bdf50532819d22cca9c3b6a5ab6a28fc3cc71a2/.github/workflows/deploy.yml#L33

If these options were not specified, the existing redisearch volume (https://github.com/legumeinfo/gcv/blob/8bdf50532819d22cca9c3b6a5ab6a28fc3cc71a2/microservices/compose.prod.yml#L44-L45) containing the redis db would be retained/reused (and not reloaded).

I'm not sure if these options are actually still relevant/needed; I should revisit the issue that caused their inclusion in the first place.

**Comment by adf-ncgr** [comment]
As long as you're OK with it (>=1/4 hr deployment) I can live with it. 

@cann0010 do you want me to go ahead and add the Trifolium subterraneum and new Cajanus cajan genomes (older Cajanus is not working for some reason)? I figured we would keep Wm82 as the representative soybean genome for the LIS GCV but can add the new Lee if desired to the soybase GCV set. 

@nathanweeks do you want me to fill in the details of a comparable load script for soybase genomes of interest? Although following the basic model we've established for LIS should be easy enough, there may be some data-debugging involved...

**Comment by nathanweeks** [comment]
> @nathanweeks do you want me to fill in the details of a comparable load script for soybase genomes of interest? Although following the basic model we've established for LIS should be easy enough, there may be some data-debugging involved...

That would be much appreciated! But if you just want to sketch an outline and leave data-debugging issues to other parties, that's perfectly acceptable.

**Comment by nathanweeks** [comment]
> > @nathanweeks do you want me to fill in the details of a comparable load script for soybase genomes of interest? Although following the basic model we've established for LIS should be easy enough, there may be some data-debugging involved...
> 
> That would be much appreciated! But if you just want to sketch an outline and leave data-debugging issues to other parties, that's perfectly acceptable.

... and I'll add that most things soybase are probably lower-priority than most things legumeinfo at this point ...

**Comment by sammyjava** [comment]
This is done in that https://gcv.legumeinfo.org/ seems to be a thing that exists, and I've updated the resources and tools to use that URL (which is now on dev).
