### ISSUE TITLE
Rename repository

### ISSUE THREAD

**Issue by alancleary** [legumeinfo/jekyll-legumeinfo#7]
I don't think "jekyll-emaple" is quite apt for a site that's running in production. Perhaps the name should just be the site's domain - "legumeinfo.org". I'm open to suggestions, though.

**Comment by adf-ncgr** [comment]
how about in keeping with the other one we make this "jekyll-legumeinfo" ?

**Comment by alancleary** [comment]
Done via GitHub settings.
