### ISSUE TITLE
non-ASCII characters not displaying properly on the new site

### ISSUE THREAD

**Issue by adf-ncgr** [legumeinfo/jekyll-legumeinfo#84]
non-ASCII characters are not being displayed to best advantage; see for example https://jekyll-dev.lis.ncgr.org/collections/phaseolus/ and search for Blair_Cort or Xana_x_Cornell49242

**Comment by sammyjava** [comment]
Good catch! It's in my python parser:
```
_data/taxa/Phaseolus/species_collections.yml:    - collection: BAT93_x_JALOEEP558.gen.Blair_Cort%C3%A9s_2018
_data/taxa/Phaseolus/species_collections.yml:    - collection: mixed.gen.Blair_Cort%C3%A9s_2018
```
will fix but let's not let this be a blocker for launch.

**Comment by sammyjava** [comment]
Whoa. This fixed itself when I switched to parsing from local files pulled from GitHub. It was an HTTP issue.
