### ISSUE TITLE
Notification of new taggage?

### ISSUE THREAD

**Issue by sammyjava** [legumeinfo/jekyll-legumeinfo#91]
I'm wondering if we can/should put an email notification into the GA on a tag - so that certain people like Nathan and I and Andrew (because he's so danged good at finding glitches) get notified when someone has tagged main to production. Just as an oversight thing. I have "All activity" toggled for watching on this repo but didn't get any email from Nathan's or my own tags today. We should have a process in place so that stage is Q/Aed before taggage, but I know that stuff sneaks through. Plus it's just nice to know the production site has been updated.

**Comment by alancleary** [comment]
GitHub doesn't support notifications for tags. However, it does support notifications for releases, so probably the simplest thing to do is just create a release whenever you want to tag something. I think this is nice anyway because you can write a description of what's in the release, which helps keep stakeholders and users in the loop.

If we don't want to use releases then the path of least resistance is probably to use a git hook or use a service like [new(releases)](https://newreleases.io/).

**Comment by alancleary** [comment]
OK, so it sounds like you're really only interested in accommodating the technical stakeholders here, which is fine. FYI, the description portion of a release is optional.

There's also the GitHub API, which provides a tag feed: https://stackoverflow.com/a/18686243

**Comment by nathanweeks** [comment]
@sammyjava :

> As for commenting on the tag, the tag shows the commit comments, which is I think even better since you don't rely on the tagger to summarize all changes (which he/she is likely to not know). For example, the one I did this morning:
> 
> https://github.com/legumeinfo/jekyll-legumeinfo/releases/tag/2022-04-06.2
> 
> ~I'm pretty sure that if there were, say, eight commits to main since the previous tag, the tag would show all eight commit comments.~ [Dang, turns out to not be true, as evidenced by looking at 2022-04-06.1 vs the previous.]

To get a listing of commits between two tags, use the `https://github.com/<org>/<repo>/compare/<ref1>...<ref2>` syntax; e.g.:
https://github.com/legumeinfo/jekyll-legumeinfo/compare/2022-04-06.1...2022-04-06.2
 
> It's also interesting, I just noticed that tags generate zip and tarballs as well; I thought that was just releases. It seems that git has a lot of crossover between branches, tags, and releases.

I think this is GitHub auto-generating tarballs on-demand from any ref (including a commit), like the auto-generated tarballs when you click on "Code > Download zip" (e.g., https://github.com/legumeinfo/jekyll-legumeinfo/archive/refs/heads/main.zip or a specific commit like https://github.com/legumeinfo/jekyll-legumeinfo/archive/a2d68b446e7ecb700c471e4233fb0b3c1be8da0d.zip)

@alancleary :
> There's also the GitHub API, which provides a tag feed: https://stackoverflow.com/a/18686243

Neat! That looks like a nice low-tech technical solution :-) 

That said, my main reasons for shying away from GitHub releases were (1) a preference for using pure `git` (the CLI tool) to automate releases, without having to switch to the web interface (or another tool, like the GitHub CLI), and (2) a misconception (?) that such releases auto-generated a physical tarball that consumed from some organization/repository quota (e.g., related to GitHub Packages)---I don't think this is true for public repos, though?

I'm not aware of a practical reason to avoid GitHub releases for deployment, though. GitHub releases also create git tags that are visible via the `git` CLI, so they aren't exactly non-portable.

**Comment by sammyjava** [comment]
I can imagine using release to indicate something functional. A tag increment may be fixing a typo or adding a news item, something mundane. A release increment would indicate that we've added a new section to the website or new functionality, or maybe even a new species, less mundane, as in what one thinks of with a "software release."  *Thinking out loud.*

**Comment by alancleary** [comment]
"Release is a release is a release" -- Gertrude Stein

What Stein was trying to say is that anything that changes the semantic version of the software, major or minor, is a release.

Seriously, though, I think releases are a totally reasonable mechanism to use here: they give us the email notifications we want, they don't impact our quotas ([as far as I can tell](https://docs.github.com/en/repositories/releasing-projects-on-github/about-releases#storage-and-bandwidth-quotas)), and they let anyone who wants to track our release (major or minor) do so without jumping through hoops. Not to mention virtually every repo I use on GitHub that versions their software uses releases after hitting version 1, or even before!

**Comment by alancleary** [comment]
> I'm glad you didn't use "There's no there there." :)

I missed a release, though. There should've been 4!

**Comment by alancleary** [comment]
Looking into the GitHub release docs a little more; apparently you can [auto-generate release notes](https://docs.github.com/en/repositories/releasing-projects-on-github/automatically-generated-release-notes). Very cool!

**Comment by sammyjava** [comment]
So in writing the Wiki routine updates how-to I wanted to do everything in the GitHub web interface. It turns out you cannot simply create a tag in the web interface - you have to create a release as well, it's only done through the new-release UI. At least I looked at a lot of docs and posts and that appears to be the case.

So, in the end, the way the web interface works makes us create new releases for promotions to production when we use the web UI, which makes me think we should create tag+release in general for consistency. I don't want to limit updating the site to command-line git usage.
