### ISSUE TITLE
contact email isn't contacting me

### ISSUE THREAD

**Issue by adf-ncgr** [legumeinfo/jekyll-legumeinfo#92]
The contact page link is currently set to lis@ncgr.org which I think we provisionally agreed would be sent to me for triage. My test message hasn't come through and is not in spam...

**Comment by sammyjava** [comment]
Tests sent from my crib. Dunno why it wouldn't work. No bounce.

**Comment by sammyjava** [comment]
(NCGR email aliasing issue, of course, not jekyll-legumeinfo.)

**Comment by adf-ncgr** [comment]
seemingly google won't let you email yourself through an alias. As long as it's working for others, I guess it's fine. Except that all those emails adf_past@ncgr.org sent to adf_future@ncgr.org will be in vain...
