### ISSUE TITLE
Add requirements.txt for Python scripts

### ISSUE THREAD

**Issue by alancleary** [legumeinfo/jekyll-legumeinfo#94]
PR #93 noted "the scripts require Python 3.9+ because of newer features of pyyaml that are used. That's why the build-data-yaml runner explicitly invokes python3.9." Rather than explicitly using Python 3.9 in the scripts, a `requirements.txt` file should be provided that specifies exactly what version of pyyaml should be installed. That way people that don't have Python 3.9 installed (e.g. I have 3.10) can use the scripts verbatim and are guaranteed to have the correct version of pyyaml installed.

You can create a `requirements.txt` file as follows:
```
pip freeze > requirements.txt
```
(If you're using system level libraries then you'll want to grep for pyyaml.) Then people that want to use the scripts just have to run:
```
pip install -r requirements.txt
```

**Comment by sammyjava** [comment]
Good stuff. The pyyaml version I've got installed with python39-pyyaml is 5.4.1 so as I understand it, this should do the trick:
```
$ cat requirements.txt 
pyyaml >= 5.4.1
```
If so, I'll add it.

**Comment by sammyjava** [comment]
(And switch to python3 in the runner.)

**Comment by alancleary** [comment]
The major version should be capped so we don't get bit by breaking changes in  a major release:
```
pyyaml >= 5.4.1, < 6
```
Otherwise everything sounds good!

**Comment by sammyjava** [comment]
Done, for this case. I'll be sure to update requirements.txt for any future picky versions.
